### ISSUE TITLE
Create directory for stdio in job array

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#116]
If more than one task per job is submitted, set default path to ``job-%{JOB_ID}/stdout-%{TASK_ID}`` resp ``job-%{JOB_ID}/stderr-%{TASK_ID}``. Make sure that job-%{JOB_ID} is successfully created.

**Comment by Kobzol** [comment]
Closed by https://github.com/It4innovations/hyperqueue/pull/122.
