### ISSUE TITLE
Hq Dashboard Tasks

### ISSUE THREAD

**Issue by vyomkeshj** [It4innovations/hyperqueue#135]
- [x]  Hardware Monitoring [Monitor the workers' hardware utilization]
    - [x] Network
    - [x] CPU
    - [x] Memory

- [ ] Postmortem Replay from log for hw-monitoring
 
- [x] Event Logging

**Comment by spirali** [comment]
* [ ] htop-like progress bar for CPU utilization (aggregated per worker)
* [ ] Working keyboard control
* [ ] Reasonable display visualization when no workers are connected (not just blackscreen)
* [ ] Possibility to show worker details (Information from worker config)
* [ ]  Chart with the number of workers in time ![image](https://user-images.githubusercontent.com/263349/136401156-bf988681-e368-4172-bf60-7a1ed3d9a3ff.png)
* [ ] Tab with progressbar as in "hq progress" per each active job

**Comment by Kobzol** [comment]
This issue is too general, we will create more granular ones.
