### ISSUE TITLE
Command ``worker top``

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#16]
Command that shows current cpu and memory utilization of workers & their running tasks.

One possible way how to implemented is to put this into "WorkerOverview" messages (current tasks are already there).

**Comment by Kobzol** [comment]
What about exposing something like `worker remote`, which will return either the address of the worker, or an SSH connection line that will allow you to run an arbitrary command on a worker? Something like
```bash
$ ssh `hw worker remote 1` top
```

**Comment by spirali** [comment]
I like the idea! (Just I would call it ``hq worker address 1``
