### ISSUE TITLE
More detailed program specification

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#24]
* [x] Specify working directory of task through ``hq submit --cwd=/a/path ...``
* [x] Specify specify stdout/stderr files ``hq submit --stdout=/a/path/file ...`` / ``hq submit --stderr=/a/path/file ...``
* [x] Substitution of "{JOB_ID}" to actual job id in paths ``hq submit --stdout=/a/path/file-{JOB_ID} ...``
* [x] Allow to specify extra env variables: ``hq submit --env PYTHONPATH=xxx --env MYVAR=yyy ...``
* [ ] Inheriting all current env variables ``hq submit --inherit-env ...``

**Comment by Kobzol** [comment]
Oh, sorry if you wanted to work on env. variables @vyomkeshj :laughing:. I assumed that the assignment was only for working directory.
