### ISSUE TITLE
Is hyperthreading automatically detected?

### ISSUE THREAD

**Issue by giovannipizzi** [It4innovations/hyperqueue#244]
On one of our machines, we have 128 physical cores on each node, but with hyperthreading. `hq` detects 256 CPUs (8x32). However, some of our applications are CPU-intensive and are actually slowed down when using 256 MPI processes, and need to be run on 128 maximum. 
Is there a way for `hq` to detect hyperthreading, and a way to send jobs and say "I don't want to use hyperthreading"? In particular, I want to be able to submit 128-core jobs to `hq` and guarantee that it only puts 1 per node, and not 2 per node at the same time.

**Comment by Kobzol** [comment]
You can specify cores that should be used by a specific job (e.g. `hq submit --cpus="8 compact", see [here](https://it4innovations.github.io/hyperqueue/stable/jobs/cresources/#numa-allocation-policy)) and the CPUs used by a specific worked (e.g. `hq worker start --cpus 4x4`).

It's important to understand that these core IDs are purely virtual, they only serve as virtual resources for scheduling inside of HQ. Once a task is executed, it will not be pinned to these core IDs by default.

If you want to pin the task to specific core IDs, you can either do that manually (by reading the assigned core IDs from environment variable `$HQ_CPUS` and using e.g. `numactl`), or by using the `--pin` flag when submitting a job.
See [pinning](https://it4innovations.github.io/hyperqueue/stable/jobs/cresources/#pinning) documentation.

Regarding hyperthreading, even though the scheduler supports it, these is currently no way to enter individual core IDs using the CLI. If we add that, the user could say for example "I want this worker to only use core IDs 0, 2, 4, 6, 8", etc.
Or we could add a special hyperthreading mode, that would automatically detect physical cores and only use a single physical thread per each physical core.

**Comment by spirali** [comment]
I have added option --cpus="no-ht" (when worker starts) that basically tells the scheduler not to use HyperThreading. (Technically: for each physical core it ignores all virtual cores other then the first one).

**Comment by Kobzol** [comment]
It is also possible now to specify resources for workers started using automatic allocation (https://github.com/It4innovations/hyperqueue/pull/259).

So you can combine these two new features:
```bash
$ hq alloc add pbs --cpus="no-ht" --time-limit 1h -- -q qexp -A ProjectA
```

**Comment by giovannipizzi** [comment]
Cool! Is it possible to combine it with other options? E.g. `--cpu="8 no-ht"`? (maybe not critical for our usecase, though).

Also, out of curiosity, what is your release schedule? At the moment we're using your precompiled binaries. I guess however, for testing, we can use your nightly-built binaries? (so we can get this feature in tomorrow's build?)

**Comment by Kobzol** [comment]
Currently, it cannot be combined, but it sounds reasonable, we'll think about it.
We usually release a new version of HQ every month and a half or so, but it depends a lot on the fact if new features are available.

To use the "latest and greatest" version, you can use the nightly build. It's built every night with the version from the `main` branch. So in tomorrow's build you should be able to use `no-ht`. You can find the nightly builds [here](https://github.com/It4innovations/hyperqueue/releases/tag/nightly).

**Comment by spirali** [comment]
FYI We have added possibility to specify core ids including information how they are "NUMA grouped". E.g. ``--cpus=[[0,1,3], [10, 11, 12]]``. This allows to manually select a subset of cores while avoiding HyperThreading siblings.
