### ISSUE TITLE
Autoallocation fails with Slurm on nightly build

### ISSUE THREAD

**Issue by mbercx** [It4innovations/hyperqueue#261]
Thanks a lot for the quick responses to the issues so far! I started playing around with the nightly build release, and got the following error when HQ tries to submit to Slurm:

```
$ [2021-12-14T21:50:08.539Z ERROR hyperqueue::server::autoalloc::process] Failed to queue allocation into queue 1: sbatch execution failed
    
    Caused by:
        Exit code: 255
        Stderr: sbatch: error: getcwd failed: No such file or directory
        Stdout:
```

Here is the command I executed to set up the autoallocation:

```
hq alloc add slurm --backlog 1 --workers-per-alloc 1 --time-limit 30m --name debug -- --partition=debug -A mr0 -C mc
```

Replacing the binary back with the v0.6.1 one and restarting the server fixes the issue.

**Comment by Kobzol** [comment]
Thanks for the error report. The error looks quite weird, I cannot reproduce it on a PBS nor a Slurm system. Is it possible that either `$HOME/.hq-server` or the directory from which you started `hq server start` got deleted in the meantime? From the error it looks like the server tries to run `sbatch` but it finds itself inside a missing directory.

You can try to run the HQ server with debug logging (`RUST_LOG=hyperqueue=debug hq server start`) and then you should see something like that when an allocation is being submitted:
```
Running command `sbatch <path-to-script>`
```
Could you please post the contents of the script at the specified path?

**Comment by mbercx** [comment]
Indeed, it was unrelated to the new version, but caused by the fact that I started the server from a folder that was later deleted. Here's the `stderr` from the server with running in debug mode:

```
[2021-12-14T23:16:12.034Z DEBUG hyperqueue::server::autoalloc::process] Running autoalloc
[2021-12-14T23:16:12.086Z DEBUG hyperqueue::server::autoalloc::descriptor::common] Running command `sbatch /users/mbercx/.hq-server/001/autoalloc/debug/001/hq-submit.sh`
[2021-12-14T23:16:12.098Z ERROR hyperqueue::server::autoalloc::process] Failed to queue allocation into queue 1: sbatch execution failed
    
    Caused by:
        Exit code: 255
        Stderr: sbatch: error: getcwd failed: No such file or directory
        Stdout: 
```

The error should be easy to reproduce:
1. Create a new directory, cd into it and start the server in the background:
  ```
  RUST_LOG=hyperqueue=debug hq server start 2> $HOME/stderr > $HOME/stdout &
  ```
2. Start a new allocation:
```
hq alloc add slurm -b 1 --time-limit 30s
```
3. Remove the directory and try to submit an HQ job:
```
hq submit echo "Hello world"
```

**Comment by Kobzol** [comment]
Ok, thanks for the reproduction. We could change the auto allocator to use a different directory for submitting allocations, but I suspect that deleting the directory from where the server was started could have further unintended consequences in other parts of HQ.

Why do you delete the directory?

**Comment by mbercx** [comment]
> Why do you delete the directory?

This was just a coincidence, I just was't aware that this would influence the operation of HQ. Would it not be possible to simply execute all commands from the server directory?

**Comment by Kobzol** [comment]
I suppose that we can do that :) I'll change it.
