### ISSUE TITLE
Drop requirement that submission script needs to be executable

### ISSUE THREAD

**Issue by giovannipizzi** [It4innovations/hyperqueue#263]
At the moment, the submission script needs to be executable (have the `x` permission bit).
I think I understand why this is the case (HQ will just execute the script when the time comes). But in most other schedulers, this is not a requirement (just tested on SLURM, and I think also in all other schedulers we support, we don't set the executable bit).

Is this a requirement that you think can be dropped? (e.g. checking if the first line is a shebang, i.e. it starts with `#!`, and then executing it with that shell in that case).

Indeed, in slurm, if the script does not start with a shebang, execution stops, so I imagine this is exactly what SLURM does:
```
$ sbatch run.sh
sbatch: error: This does not look like a batch script.  The first
sbatch: error: line must start with #! followed by the path to an interpreter.
sbatch: error: For instance: #!/bin/sh
```

**Comment by Kobzol** [comment]
HyperQueue simply executes whatever it receives as a command. If you want to execute the script directly, you can use
```bash
$ hq submit -- script.sh
```
If you want to execute it with a specific bash, you can use
```bash
$ hq submit -- bash script.sh
```

Currently, we'd like to avoid parsing the input, as it might not even be a script, but an executable. Probably after we flesh out the design of https://github.com/It4innovations/hyperqueue/issues/6, this decision will change, but we need to think about how that should work.

Is it problematic for your use case to make the script executable or to use `hq submit bash script.sh`?

**Comment by giovannipizzi** [comment]
Thanks for the feedback! I understand your point - we can work around and make the script executable for now (maybe we'll think if we should always do it as a general rule). I was just wondering if the other schedulers have a good reason to allow non-executable scripts?

**Comment by Kobzol** [comment]
Well, HQ works quite differently than PBS/Slurm (it's a different tool with different usecases after all). Currently, we don't interpret the script in any way, but PBS/Slurm has to, because the file usually contains directives (`#PBS`/`#SBATCH`). Therefore it's more like a text input for them, but for us it's just a blackbox executable (binary or a script).

If we decide to implement something like `#HQ`, this would probably change. But this interacts with a lot of other things, we are also preparing a Python API, so we want to make sure that it can all work together.

**Comment by spirali** [comment]
In general, we want to support #HQ directives, so parsing the beginning of a submitted script is inevitable, so parsing #! should not be hard.

**Comment by goxeq** [comment]
I would like to react to this: "Is it problematic for your use case to make the script executable or to use hq submit bash script.sh?"

The problem with that is that you command is then listed as "bash" in `hq jobs`, and this would be identical for all jobs even if actual scripts are named differently.

**Comment by Kobzol** [comment]
I see. Well, the default name of a job is really just a very crude guess based on the first executed command, as you have probably noticed, and it usually won't be very useful.

I suggest that you use the `--name` flag when submitting a job to name your submissions in a more intuitive way:
```bash
./hq submit --name script.sh -- bash ./script.sh
```
