### ISSUE TITLE
Implement a basic set of benchmarks

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#27]

**Comment by Kobzol** [comment]
Benchmarks of what? :)

**Comment by spirali** [comment]
HQ :)

Basically tests that if you submit many jobs or submits large job array, connect many workers, that HQ is not a performance bottleneck.

**Comment by Kobzol** [comment]
Ok, I will try to prepare something.

**Comment by spirali** [comment]
Thank you. What I want is just more-or-less a sanity check rather then highly-sophisticated benchmarks.
