### ISSUE TITLE
"hq submit help" submits a job "help" instead of showing help

### ISSUE THREAD

**Issue by goxeq** [It4innovations/hyperqueue#310]
For subcommands like alloc, "hq alloc help" works the same way as "hq help alloc". But this is not the case for submit, which is not very intuitive.

**Comment by Kobzol** [comment]
Hi! If you want to get help for some command, please use the `--help` flag:
```bash
$ hq alloc --help
$ hq submit --help
```

`hq help alloc` and so on shouldn't work at all, we will probably disable it in the next version.
