### ISSUE TITLE
Complex array definitions

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#36]
Implement more complex array definitions:

The following should work:

``hq submit --array=1,2,7-10,25-40:5,110 ...``

That is equivalent to run array on ids: 1,2,7,8,9,10, 25, 30, 35, 40, 110

* Include a test that all ranges are non-overlapping.

**Comment by Kobzol** [comment]
Related to https://github.com/It4innovations/hyperqueue/issues/52.
