### ISSUE TITLE
Handle a large ammont of stdout/stderr files

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#42]
In case of array jobs with many tasks produce many stdout/stderr file on shared fs. Introduce an option that writes these files into a ramdisk (or /tmp) and only if a task fails its stdout/stderr are written to a final destination

**Comment by Kobzol** [comment]
When should the generated files be removed? It's unclear whether following jobs/taks will need to use them. They will not be accessible from another node anyway.

**Comment by Kobzol** [comment]
Fixed by https://github.com/It4innovations/hyperqueue/pull/100
