### ISSUE TITLE
Task output is still too wide in practice

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#426]
Task output is still too wide in practice

So make it less wide.

Random ideas:
* Error message on new row rather column? (This can be especially problematic with custrom errors, e.g. from Python API, that can be long and multiline)
* If stdout/stderr is relative to workdir, then just use some placeholder shortcut?
* Hostname column seems to deplete to much space

![image](https://user-images.githubusercontent.com/263349/170047844-dc255c3c-aa52-4fe9-b2cf-1ee430cc9d82.png)

**Comment by Kobzol** [comment]
I'm not sure how to make the table less wide yet (maybe split each row into multiple rows), but I'd rather not introduce placeholders here. The goal of resolving placeholders in this table was to allow the user to easily copy the path and then read it/work with it. Introducing placeholders would make this harder.

**Comment by spirali** [comment]
Unfortunatelly, it is still too wide in practise :)

![image](https://user-images.githubusercontent.com/263349/180240792-dae7f3aa-9df5-42b5-8107-b6908f4d06f2.png)
