### ISSUE TITLE
How to submit tasks requesting GPUs?

### ISSUE THREAD

**Issue by lahwaacz** [It4innovations/hyperqueue#455]
Hi! I'm trying out hyperqueue for the first time and I have some trouble figuring out how the GPU resource allocation is supposed to work. I guess I'm missing something...

I have hyperqueue v0.11.0 and this is what I did:

1. Started the server with `hq server start`
2. Created an allocation queue with `hq alloc add slurm --time-limit 1h --resource "gpus=range(0-1)"` (the compute nodes have 2 GPUs each, so this is supposed to run one worker per node, and each should have access to both GPUs?)
3. I submitted a job requesting 1 GPU:
```
$ hq submit --resource "gpus=1" nvidia-smi
Job submitted successfully, job ID: 3
```
4. I checked the output and it showed that no GPU was available:
```
$ cat job-3/0.stdout
No devices were found
```

Why does it not work? How can I debug this?

----

Additionally, I tried to submit a job requesting 4 GPUs on the same allocation queue (just to see how it would fail, I did not expect it to actually run): `hq submit --resource "gpus=4" nvidia-smi`

After a while, I run `hq worker list` and it showed many workers:
```
+----+---------+----------+-------------------------------------------+---------+----------------+
| ID | State   | Hostname | Resources                                 | Manager | Manager Job ID |
+----+---------+----------+-------------------------------------------+---------+----------------+
| 58 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10279          |
| 59 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10280          |
| 60 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10281          |
| 61 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10282          |
| 62 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10283          |
| 63 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10284          |
| 64 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10285          |
| 65 | RUNNING | gp11     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10286          |
| 66 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10287          |
| 67 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10288          |
| 68 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10289          |
| 69 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10290          |
| 70 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10291          |
| 71 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10292          |
| 72 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10293          |
| 73 | RUNNING | gp12     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10294          |
| 74 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10295          |
| 75 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10296          |
| 76 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10297          |
| 77 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10298          |
| 78 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10299          |
| 79 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10300          |
| 80 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10301          |
| 81 | RUNNING | gp13     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10302          |
| 82 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10303          |
| 83 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10304          |
| 84 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10305          |
| 85 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10306          |
| 86 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10307          |
| 87 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10308          |
| 88 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10309          |
| 89 | RUNNING | gp14     | 1x16 cpus; gpus Range(0-1); mem 62.51 GiB | SLURM   | 10310          |
+----+---------+----------+-------------------------------------------+---------+----------------+
```
And the job is still waiting in the queue:
```
$ hq job list
+----+------------+---------+-------+
| ID | Name       | State   | Tasks |
+----+------------+---------+-------+
|  4 | nvidia-smi | WAITING | 1     |
+----+------------+---------+-------+
There are 4 jobs in total. Use `--all` to display all jobs.

$ hq job info 4
+----------------------+---------------------------------------------------------------------------+
| ID                   | 4                                                                         |
| Name                 | nvidia-smi                                                                |
| State                | WAITING                                                                   |
| Tasks                | 1; Ids: 0                                                                 |
| Workers              |                                                                           |
| Resources            | cpus: 1 compact                                                           |
|                      | gpus: 4                                                                   |
| Priority             | 0                                                                         |
| Command              | nvidia-smi                                                                |
| Stdout               | /mnt/gp3/home/klinkovsky/stuff/cluster/hyperqueue/job-4/%{TASK_ID}.stdout |
| Stderr               | /mnt/gp3/home/klinkovsky/stuff/cluster/hyperqueue/job-4/%{TASK_ID}.stderr |
| Environment          |                                                                           |
| Working directory    | /mnt/gp3/home/klinkovsky/stuff/cluster/hyperqueue                         |
| Task time limit      | None                                                                      |
| Submission date      | 2022-07-18 17:47:07 UTC                                                   |
| Submission directory | /mnt/gp3/home/klinkovsky/stuff/cluster/hyperqueue                         |
| Makespan             | 25m 29s                                                                   |
+----------------------+---------------------------------------------------------------------------+
```

I don't really understand what's happening, but it seems to be unwanted behavior that should not happen. Why did hyperqueue spawn so many workers when it can determine that they can't execute the job?

Also, why does `hq job list` show so little information? For example a column for "Resources" would be useful so that I don't have to run `hq job info` for each job.

**Comment by lahwaacz** [comment]
> If you run nvidia-smi and there do not seem to be any GPUs, mostly likely the nodes provided by Slurm simply do not have GPUs available, or some module has to be loaded in order for them to be available.

No, there are no modules necessary to make GPUs (or nvidia-smi) available on the compute nodes. The only thing is GPU allocation in Slurm. If I run simply `srun nvidia-smi`, I get `No devices were found` too, but running `srun --gpus 2 nvidia-smi` actually shows the GPUs.

I guess I should run `hq alloc add slurm --time-limit 1h --resource "gpus=range(0-1)" -- --gpus 2` instead? But the [documentation](https://it4innovations.github.io/hyperqueue/stable/jobs/gresources/) does not mention the `--gpus` parameter (or `--gres` or the equivalent for PBS). Instead, it mentions automatic detection (but for `hq worker start`, not `alloc`, so it does not apply but it still confused me).

---

Actually, what brought me to hyperqueue is this use case. The accelerated nodes on Karolina have 8 GPUs, but I'd like to submit tasks using fewer GPUs and still utilized the node as efficiently as possible. I was hoping to create an 8-GPU allocation in hyperqueue and let it manage the workers for tasks using e.g. 1, 2 or 4 GPUs. Are there some examples specifically for Karolina? I'm not sure what is the best way to start this up and I still don't know how to configure the `--resource` parameter to allow multiple workers per node, but also satisfy tasks requesting any number of GPUs at the same time.

**Comment by lahwaacz** [comment]
OK, I get it now. I think, though, that having all GPUs on the node are provided by default is bound to the scenario where every job allocates the entire node. I don't know if this is more common than the case where nodes are shared for multiple jobs and users have to explicitly allocate the cores and GPUs they want. I agree the documentation should be as general as possible, but that also means that both these cases should be considered. 

As for the automatic detection, have you considered offloading the detection that `hq worker start` does to the trial allocation that `hq alloc add` submits? As far as I understand, you'd just need to read the result from an external process, but it should be valid because the allocations submitted later would still get the same resources.

Thanks for the clarification, I think that I can make it work now, so I'll close this issue. I'll create a new one if I need anything.

**Comment by Kobzol** [comment]
For HyperQueue, in most cases it doesn't really make sense to use anything else than 1 node = 1 worker. The worker should thus "occupy" all the resources of the given node. That doesn't mean that HQ tasks will occupy the whole node though, the advantage of HQ is that you can run many tasks in parallel on that single worker, and HQ will make sure that the resource requirements will be upheld.

**Comment by Kobzol** [comment]
> As for the automatic detection, have you considered offloading the detection that hq worker start does to the trial allocation that hq alloc add submits? As far as I understand, you'd just need to read the result from an external process, but it should be valid because the allocations submitted later would still get the same resources.

I'm not sure what exactly do you mean by this. Do you mean that when `hq alloc add` does a test allocation, it should also try to start a worker with the provided parameters (e.g. resources)? The trial allocation doesn't actually allocate anything to save resources, it just performs a basic sanity check that the job manager (Slurm/PBS) will not outright reject the provided parameters.

**Comment by lahwaacz** [comment]
Oh, so the trial allocation is cancelled as soon as it lands in the PBS/Slurm queue? I thought HQ actually waits until it is actually started on a node before it cancels the allocation. In that case, it would be a little bit more work, but since the point of the automatic allocation is to start workers, I don't see a problem with starting a trial worker for a couple of seconds to detect the resources.

**Comment by Kobzol** [comment]
We ran into some trouble with spamming too much PBS allocations, so we try really hard to avoid creating running allocations if it's not required, that's why it works in this way.

I wonder what would be the usecase for that? You would like to know what resources will be auto-detected on a given node? I guess that you could just execute `srun hq worker start` or `qsub hq worker start` or something like that to find that out. That should be a one-time event and it shouldn't have to be done everytime you run `hq alloc add`.

**Comment by spirali** [comment]
For completeness, let me note that you can run
```hq worker hwdetect```
This prints what resources can worker detect automatically. Command immediately terminates and does not start the worker.
