### ISSUE TITLE
--idle-timeout for hq alloc add is missing

### ISSUE THREAD

**Issue by lahwaacz** [It4innovations/hyperqueue#456]
The `hq worker start` and `hq server start` commands have an [--idle-timeout](https://it4innovations.github.io/hyperqueue/stable/deployment/worker/#idle-timeout) parameter, but `hq alloc add` does not have this parameter.

**Comment by lahwaacz** [comment]
I agree that 5m is a good default value. In my use case I wanted to decrease the idle timeout for testing, because when I run `hq alloc add pbs --time-limit 10m` to avoid any long-running workers and submitted several tasks with `--time-request` set to 5m or similar, I often ended up with multiple workers running and waiting uselessly.

**Comment by spirali** [comment]
I agree that we should expose idle timeout to auto alloc. We should probably print some warning when idle timeout is too big (Lets us say >1h), but we should definitely allow to decrease the value under the default.

**Comment by Kobzol** [comment]
I agree. I posted https://github.com/It4innovations/hyperqueue/pull/457 to resolve this.
