### ISSUE TITLE
Task array build from file

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#47]
Implement analogue of "parallel -a ..."

**Comment by Kobzol** [comment]
Was this resolved by https://github.com/It4innovations/hyperqueue/pull/50? Or is there another usecase that needs a separate command per each line?

**Comment by spirali** [comment]
In some sense yes ... and no :)

[To fully implement "-a" we also need merging of results into one file without creating intermediate files, which needs to reenable dependencies (internally, not necessarily as public API), that needs to finish two things: having multiple outputs and snapshoting, and snapshoting needs to solve pure/unpure tasks. So there is still a long way].
