### ISSUE TITLE
Relaxation of the job-name character limit

### ISSUE THREAD

**Issue by abhi18av** [It4innovations/hyperqueue#485]
Hi team 👋 

I was exploring the experimental Nextflow support for hyperqueue and it seems that for real workloads, the character limit for job names is somewhat problematic.

## Steps to reproduce 

1. Setup `hq` server and worker 
2. Run the [`rnaseq-nf` workflow](https://github.com/nextflow-io/rnaseq-nf/) using the following command 

```
$ NXF_VER=22.08.2-edge nextflow run nextflow-io/rnaseq-nf -process.executor hq -profile docker

```

This fails with the following error message 

```
Error executing process > 'RNASEQ:INDEX (ggal_1_48850000_49020000)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  hq --output-mode=json submit --directives=file .command.run

Command exit status:
  1

Command output:
  {
    "error": "name cannot be more than 40 characters"
  }
```

3. Upon inspecting the generated `.command.run` file, the problem seems to be that the `--name` argument expects a string less that 40 characters.

```
$ head .command.run
#!/bin/bash
#HQ --name nf-RNASEQ_INDEX_(ggal_1_48850000_49020000)
#HQ --log /home/biodragon/data/_scratch/work/e2/c7416a42cdf987959f3edafa6d17c6/.command.log
#HQ --cwd /home/biodragon/data/_scratch/work/e2/c7416a42cdf987959f3edafa6d17c6
# NEXTFLOW TASK: RNASEQ:INDEX (ggal_1_48850000_49020000)
...
...
```

## Context 

I'm raising this here since these names can get longer depending on the design of a pipeline in DSL2 version for example, take the full fledged `nf-core/rnaseq` pipeline which would have workflow/sub-workflows/modules in the names.

This might be addressed on the Nextflow side as well, but trimming the generated name for the shell script, however I felt that it's worthwhile to raise it here first.

**Comment by Kobzol** [comment]
Hi :) This issue was brought up recently (https://github.com/It4innovations/hyperqueue/issues/482) and it was already resolved (https://github.com/It4innovations/hyperqueue/pull/483). The change will appear in the next HyperQueue release.

**Comment by abhi18av** [comment]
Ah, this is great - best fixes are the ones already done 👍
