### ISSUE TITLE
Running on pre-emptible batch queue crashes allocation queue in the HyperQueue

### ISSUE THREAD

**Issue by svatosFZU** [It4innovations/hyperqueue#501]
On Karolina HPC, I am running  on pre-emptible queue: qcpu_preempt queue (https://docs.it4i.cz/general/resources-allocation-policy/). It means that some or all of my jobs can be killed at any moment. I have noticed that my HyperQueue allocation queue keeps disappearing. So, I ran HyperQueue server with debugging:

RUST_LOG=hyperqueue::server::autoalloc=debug hq server start

The relevant part of the output is

2022-09-29T13:35:31Z DEBUG Handling message WorkerLost(WorkerId(101), ManagerInfo { manager: Pbs, allocation_id: "1508524.infra-pbs", time_limit: None }, ConnectionLost)
2022-09-29T13:35:31Z DEBUG Removing worker 101 from allocation 1508524.infra-pbs
2022-09-29T13:35:31Z DEBUG Attempt to refresh allocations of queue 1
2022-09-29T13:35:31Z DEBUG Refresh attempt was rate limited
2022-09-29T13:35:31Z ERROR The queue 1 had too many failed allocations, it will be removed.

As it is normal and expected that jobs would be killed on pre-emptible batch queue, is there some switch that would stop this check and kept the allocation queue running?

**Comment by Kobzol** [comment]
This is interesting. I haven't really considered pre-emptible queues when we were designingg the autoallocator. The problem this check is trying to solve is that if something is wrong (bad configuration of the worker, HQ binary missing etc.), and the HQ worker crashes on startup for some reason, it would just endlessly spam new workers forever that crash immediately, which is not ideal.

In pre-emptible queues, the crashes are expected, but it's still not trivial to distinguish an expected crash from an unexpected one :) It looks like the PBS allocation is killed forcefully and pretty fast, because the worker did not sign out correctly.

Two solutions come to mind:
1) Only consider the allocation to be failed if it crashes very soon (i.e. < 1 minute after it has been started).
2) Add a flag to autoalloc to increase the limit of failed allocations before an allocation queue gets removed.

@spirali WDYT?

**Comment by spirali** [comment]
I am not able to find any information if we can distinguish a lost of worker because of preemption from a crash. But I would guess that it has to be stored somewhere in qstat or it should receive some kind of a signal.

If we cannot distinguish this, than we have to add a flag that would disable the safety mechanism that cancels failing allocation. But it has to be something like ``--do-not-cancel-failling-allocation-i-know-what-I-am-doing``

**Comment by svatosFZU** [comment]
I think the first option would be the way to go. The limit on failed allocation would be hard to estimate. If I would fill the HPC with small jobs and they were all killed then there could be hundreds or even thousands failures.

**Comment by Kobzol** [comment]
@svatosFZU Could you please check HQ from [here](https://github.com/It4innovations/hyperqueue/suites/8555419184/artifacts/382208300), if it has solved this issue? It should not consider workers that fail after more than a minute as "allocation failure" and should thus not trigger the rate limiter and kill the allocation queue.

**Comment by svatosFZU** [comment]
OK, I have cleaned HQ dir and started server from the archive. Lets see how it behaves over the weekend.

**Comment by svatosFZU** [comment]
Unfortunately, the allocation queue died on Sunday evening. It lasted for days, so that is improvement. So, I guess we would need the switch to ignore the failing jobs.
Could there be a possibility to "pause" the allocation queue instead of killing it? That way at least files would not pile in .hq-server/001/autoalloc/* .

**Comment by svatosFZU** [comment]
Unfortunately, I don't know. When I was using the hyperqueue::server::autoalloc=debug before, it was writing the error into the terminal (I did not see any logs). And as I cannot have the terminal constantly connected, I did not use the debug option.

**Comment by Kobzol** [comment]
I see. FWIW, if you want to see the "terminal output" of a program over a longer term, even after you disconnect, you can use something like `tmux` and run the server inside of it. Then you can connect to it later and see the output.

Allocation queue pausing is definitely in our TODO list, it's useful also for other use-cases. I will try to implement it this week.

**Comment by svatosFZU** [comment]
Thanks. When we are at it, would it be possible to have option to store the output of debug in a log file? Not just that it makes tmux, etc. unnecessary but it is also easier to process.

**Comment by Kobzol** [comment]
Can't you just run this?
```bash
$ RUST_LOG=hyperqueue=debug hq server start 2> hq-debug-output.log
```

Come to think of it, to keep the HQ server alive, you have to start it in tmux or something like that, otherwise it would be killed once you disconnect from the cluster. What tool do you use for that?

**Comment by svatosFZU** [comment]
There is no tool. I just run "hq server start &"

**Comment by Kobzol** [comment]
Not even `nohup`? If you connect to a server using `ssh` and start something with `&`, it's usually killed by SIGHUP once you close the SSH session. But it doesn't really matter I guess.

Is the redirection to a file with `2>` a working solution for you?

**Comment by svatosFZU** [comment]
The & seems to be working even after I log out. I will test the redirection later. Stopping the hq server and starting it again means loosing are job, doesn't it?

**Comment by Kobzol** [comment]
Yes, the server is not resilient at the moment.

**Comment by spirali** [comment]
For completeness: you can start worker as follows: ``hq worker start --on-server-lost=finish-running`` and it will finish currently running jobs when server is lost. But reporting of these jobs is lost.

**Comment by Kobzol** [comment]
@svatosFZU Could you please run the autoallocation queue with the version from the linked PR again, with debug logs? It would be really useful for us to see why has the queue been removed, otherwise we can't be sure that the new change is working properly.

**Comment by svatosFZU** [comment]
Sure, I started draining the machine about two hours ago. Once it is empty, I will run with the debugging.

**Comment by svatosFZU** [comment]
The allocation queue crashed during the weekend again and it was indeed with

2022-10-09T11:04:00Z ERROR The queue 1 had too many failed allocations, it will be removed.

**Comment by Kobzol** [comment]
Ok, it seems that we will have to debug this further. Could you please send us the commands that you use to create the autoalloc queue and also some brief description of the pipelines that you execute (number of jobs, number of tasks per job, duration of individual tasks)?

**Comment by Kobzol** [comment]
That would be great! You can send it to my e-mail if it contains sensitive data.

**Comment by svatosFZU** [comment]
Well, it is 150 MB. So, not for email. 
And for sensitive data, that is what I wanted to ask. Does HyperQueue print sometgin sensitive into the debug? I am just asking if I can put is in somewhere public.

**Comment by Kobzol** [comment]
The log will contain your username, various file paths used for executing jobs and also the programs and their arguments that are executed in HQ jobs.

**Comment by svatosFZU** [comment]
OK, so the log is at https://www.fzu.cz/~svatosm/hq-debug-output.log

**Comment by svatosFZU** [comment]
Well, the pre-emptive kill is random from my point of view. So, it could be in few seconds, it could be in several hours.

**Comment by svatosFZU** [comment]
There was a suggestion before to have a switch that would disable the check. While this a proper solution is being investigated, could there be a nightly version with this switch (to temporarily avoid the allocation queue crash)?

**Comment by Kobzol** [comment]
We're discussing with IT4I admins to find our more about the preemptible queues.

In the meantime, I created a PR that introduces an unstable environment variable that would allow you to mostly skip the failure checks (https://github.com/It4innovations/hyperqueue/pull/522). I'll let you know once it's ready in nightly builds.

**Comment by Kobzol** [comment]
Starting with today's nightly build, you can set the (unstable) environment variable `HQ_AUTOALLOC_MAX_ALLOCATION_FAILS` when starting the server.

```bash
HQ_AUTOALLOC_MAX_ALLOCATION_FAILS=100000 ./hq server start
```

This should avoid killing the queue too soon (the current limit is `3` otherwise).

We probably found a way how to recognize that a worker has been killed by a preemptible queue, we'll try to implement a proper solution for this soon.

**Comment by svatosFZU** [comment]
Thanks. Just one question - can I combine RUST_LOG=hyperqueue=debug and HQ_AUTOALLOC_MAX_ALLOCATION_FAILS=100000 into a single command (to make the hq server ignore the kills but also to log)?

**Comment by Kobzol** [comment]
Yes, you can set how many environment variables as you want in bash :)
```bash
RUST_LOG=hyperqueue=debug HQ_AUTOALLOC_MAX_ALLOCATION_FAILS=100000 ./hq server start
```

**Comment by svatosFZU** [comment]
One interesting observation:
The nightly is quite slow to submit jobs. Over the weekend, Karolina was quite empty but the HyperQueue was making only few allocations per hour. It can be easily worked around by using backlog in allocation queue parameters, i.e. forcing it to produce some allocations. So, it is not a problem, it is just for information. But before, the HyperQueue was able to fill Karolina without the backlog.

**Comment by Kobzol** [comment]
Thanks for the observation. It is most probably caused by the fact that while HQ now doesn't pause the queue when there are a lot of errors, it still applies exponential backoff when errors happen. So HQ submits less and less often to avoid spamming PBS.

It seems that to resolve this properly we will need to detect preemptive kills accurately. We have some ideas on how to do that, but we have to implement and try them first.

**Comment by svatosFZU** [comment]
Hi,
is it possible to change parameters of active allocation queue? 
Current situation is that Karolina is mostly full, which means jobs are failing all the time with occasional peak of successful jobs. In principle, amount of failures could be easy to reduce by varying the number of created allocation (whether by HyperQueue itself or from outside). Basically, what I would like to do is a cron job which would check every half hour or hour how many successful jobs there are. If there are successful jobs, it would set backlog to 20 and run as many jobs as possible. Once the HPC is filled with other jobs and all that happens is killing (e.g. if there are no successful jobs for one hour), I would like to set backlog to 2 (to reduce number of failures and basically just pinging if there are available slots).

**Comment by Kobzol** [comment]
It is not currently possible. If you want to change the parameters, I would suggest to simply remove the queue and create a new one with new parameters.

Obviously preemptible jobs are currently not very compatible with the way the HQ auto allocator is set up. I would maybe suggest not to use HQ with preemptible jobs (and just use normal jobs) until we can figure out a better way of supporting them.

**Comment by svatosFZU** [comment]
OK, are there any drawbacks to frequently removing and adding allocation queue (apart from more and more folders would be created in .hq-server)? I don't know what happens inside, so what does happen to jobs in one allocation queue when it is removed and new one is created?
Actually, submission to HQ is much more usable with pre-emption than submission to PBS. In HQ, I have influence on important parameters which I am not allowed to change in PBS (e.g. re-runable jobs).

**Comment by Kobzol** [comment]
When an allocation queue is removed, its jobs will be canceled.

**Comment by svatosFZU** [comment]
Hi,
I have another interesting observation. During this weekend, the HQ on one login node broke (while still using HQ_AUTOALLOC_MAX_ALLOCATION_FAILS=100000) but did not crash this time. Karolina was quite empty, so it actually does not seem to be related to job kills. Basically, the HQ server was still running

[svatosm@login4.karolina ~]$ ps aux|grep hq
svatosm  20956 34.8  0.5 2265136 1459472 ?     SNl   2022 13051:46 /home/svatosm/nightly4/hq server start
svatosm  54669  0.0  0.0 112816   980 pts/43   SN+  10:06   0:00 grep --color=auto hq

but it was not responding (even attempts to stop it)

[svatosm@login4.karolina ~]$ /home/svatosm/nightly4/hq server stop
Access token found but HQ server login4.karolina.it4i.cz:42324 is unreachable.
Try to (re)start the server using `hq server start`

Caused by:
    Connection refused (os error 111)
    
In the hq-debug-output.log, following three lines kept repeating:

[2023-01-12T02:03:19.100Z ERROR hyperqueue::server::autoalloc::process] The queue 1 had too many failed submissions, it will be paused.
[2023-01-12T02:08:19.107Z DEBUG hyperqueue::server::autoalloc::process] No message received in 300000 ms, refreshing state
[2023-01-12T02:08:19.107Z DEBUG hyperqueue::server::autoalloc::process] Attempt to refresh allocations of queue 1

I can provide the entire hq-debug-output.log if that would be useful.

**Comment by Kobzol** [comment]
Hi, if you would be so kind, please send me the full log. It's a bit weird that the server was running, but it wasn't responding, maybe we'll be able to find out why from the logs.

**Comment by svatosFZU** [comment]
Here it is (it is 65 MB): https://www.fzu.cz/~svatosm/20230116-hq-debug-output-noncrash.log

**Comment by Kobzol** [comment]
From the logs it seems that the server has stopped responding, because some message that it wants to send is too big and it goes over an internal message size limit used for security reasons. This could possibly happen because some list (e.g. a list of jobs, workers or allocations) becomes too large. HQ wasn't really designed for very high amounts of jobs, so it's a new use-case for us and it's possible that HQ starts to misbehave here. I'll check the message limit to see if we can get aroudn that.

By the way, there is a large number of connections to the server from some client, are you connecting to the server repeatedly? What commands are you executing?

**Comment by svatosFZU** [comment]
OK, so here are some numbers/info. 
-I have limit of 800 jobs (waiting+running) in HQ - is that considered high amount?
-there are some commands periodically done:
--the machine which submits jobs
---periodically checks the status of jobs doing "/home/svatosm/nightly4/hq job list --filter running,waiting" (this happens usually about once per minute)
---does "/home/svatosm/nightly4/hq submit --crash-limit=1 --cpus=64 --stdout=none --stderr=none --stdin -- bash" when submitting job (this can happen several times per second but there are max tens of jobs to submit at once)
---does "/home/svatosm/nightly4/hq job cancel" when cancelling jobs (but that does not happen often)
--my job monitoring does "/home/svatosm/nightly4/hq job list --filter running,waiting" every 5 minutes
--my adaptive limits script (to minimize amount of failed jobs) does twice per hour
---"/home/svatosm/nightly4/hq job list --output-mode json --filter running"
---"/home/svatosm/nightly4/hq job info --output-mode json comma_separated_list_of_running_jobs"
---"/home/svatosm/nightly4/hq job list --output-mode json --filter finished"
---"/home/svatosm/nightly4/hq job info --output-mode json comma_separated_list_of_finished_jobs"

**Comment by Kobzol** [comment]
Hmm, 800 isn't that high, although the problem is that HQ stores all the jobs, even the finished ones, and will send these over the network e.g. in `hq job list --filter finished`. I'll investigate the message limit.

**Comment by svatosFZU** [comment]
Thanks, I basically need to know if there are some jobs that finished recently. So, if I could put some time filter (e.g. last 24 hours), that would decrease amount of jobs it returns.

**Comment by svatosFZU** [comment]
I can report another problem. This time, there was a crash. The HQ process is gone and the log ends with

[2023-01-29T07:00:23.854Z DEBUG hyperqueue::server::client] Client connection ended
[2023-01-29T07:00:24.053Z DEBUG hyperqueue::server::client] New client connection
[2023-01-29T07:00:24.084Z DEBUG hyperqueue::server::client] Client connection ended
[2023-01-29T07:00:24.114Z DEBUG hyperqueue::server::client] Client connection ended
[2023-01-29T07:00:24.285Z DEBUG hyperqueue::server::client] New client connection
[2023-01-29T07:00:24.346Z DEBUG hyperqueue::server::client] Client connection ended
[2023-01-29T07:00:24.453Z DEBUG hyperqueue::server::client] New client connection
thread 'main' panicked at 'assertion failed: tx.send(response).await.is_ok()', /__w/hyperqueue/hyperqueue/crates/hyperqueue/src/server/client/mod.rs:128:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Again, I can provide the whole log if necessary.

**Comment by svatosFZU** [comment]
Thanks for the info. Can I ask when it will be released? In the latest, I see rc1 of 0.14.

**Comment by Kobzol** [comment]
Probably in a few days, end of this week the latest.

**Comment by spirali** [comment]
My plan is to make a release this Thursday. As it seems that there are no problems so far, so it is quite probable that we will just rename v0.14.0-rc1 just to v0.14.0.

**Comment by svatosFZU** [comment]
As crashing frequency is reasonably low and there is not much the HQ can do about pre-emption, I close this ticket.
