### ISSUE TITLE
Support `--no-hyper-threading` in auto allocation

### ISSUE THREAD

**Issue by qiaojunfeng** [It4innovations/hyperqueue#531]
Hi, thanks for this awesome project! I just started using HQ, maybe I am wrong but it seems disabling hyperthreading is not available in auto allocation? For `hyperqueue v0.13.0`, it shows
```bash
$ hq alloc add slurm -t 24h --resource 'cpus=no-hyper-threading'
error: Invalid value "cpus=no-hyper-threading" for '--resource <RESOURCE>': Unexpected token found while attempting to parse resource kind, expected range or sum:
  cpus=no-hyper-threading
       |
       --- Unexpected token `no`


For more information try --help
```

Looks like this PR (#260) only disables hyperthreading when manually starting workers?
Would it be possible to have this feature in auto allocation as well? Thanks!

**Comment by Kobzol** [comment]
Hi! Good point, thanks for pointing this out. I added support for this in [this PR](https://github.com/It4innovations/hyperqueue/pull/532).

**Comment by qiaojunfeng** [comment]
Thanks a lot, I will try it out once this is merged!
