### ISSUE TITLE
Acces of $HQ_TASK_ID as environment variable

### ISSUE THREAD

**Issue by yogeshverma1998** [It4innovations/hyperqueue#536]
Hi,

I am trying to set up an array job that uses the environment variable $HQ_TASK_ID for a task job, but it is not able to access it. For example, if i run this, 

`hq submit --array 0-3 --cpus 5 --env Pol=TASK_ID --stdout run_%{TASK_ID}.out echo "$HQ_TASK_ID"`

It just output the empty files, isnt it must be the task number from 0 to 3? Can you help clearing this issue?

**Comment by Kobzol** [comment]
Hi :) This is actually a problem with bash execution order. When you execute this command, bash will evaluate `$HQ_TASK_ID` at the moment of running `hq submit`, which will probably produce an empty string.

To evaluate the code at the time of the actual HQ job being executed, you can execute e.g. this:
```console
 ./hq submit -- bash -c 'echo $HQ_TASK_ID'
```
Note the single quotes, with double quotes it will not work. It also won't work if you use single quotes, but omit `bash -c`.

**Comment by yogeshverma1998** [comment]
Thanks for the reply. Can you also tell me how to use $HQ_TASK_ID as an input to a shell script like the example given below?  But it doesn't seem to work...

`./hq submit -- bash 'run_job.sh $HQ_TASK_ID'`

**Comment by Kobzol** [comment]
Since `$HQ_TASK_ID` is an environment variable, you do not need to pass it to `run_job.sh` explicitly. You can just use `$HQ_TASK_ID` in the script directly.

**Comment by Kobzol** [comment]
Closing as this is a bash usage problem, not a HQ-related problem. Feel free to reopen if you have further questions.
