### ISSUE TITLE
Variables in --cwd definitions and --create-cwd

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#55]
Implement replacing the following strings in path provided in --cwd

- ``%{JOB_ID}%``
- ``%{TASK_ID}%``
- ``%{SUBMIT_DIR}%``
- ``%{DATE}``
- ``%{SERVER_UUID}`` -- contact @spirali for this

- Implement --create-cwd that is equivalent to --cwd but creates a directory if it exists (it will create the directory on worker!).
(add a boolean flag in submit definitions that cwd should created)

**Comment by Kobzol** [comment]
Just a note: working directory should be resolved with placeholders first, then it can be used as a placeholder in stdout/stderr.
e.g.
cwd: `/home/user/jobs/%{DATE}` -> turns into
cwd: `/home/user/jobs/123456789`

stdout: `%{CWD}/stdout` -> turns into
stdout: `/home/user/jobs/123456789/stdout`
