### ISSUE TITLE
Linux specific since version 13

### ISSUE THREAD

**Issue by Nithador** [It4innovations/hyperqueue#553]
Version 13 and up cannot be compiled on Macbook Pro with M1 processor macOS Ventura 13.1, but the problem seems to be linux specific call.

error[E0425]: cannot find function `prctl` in crate `libc`
   --> crates/tako/src/launcher.rs:160:29
    |
160 |             let ret = libc::prctl(libc::PR_SET_PDEATHSIG, libc::SIGTERM);
    |                             ^^^^^ not found in `libc`

error[E0425]: cannot find value `PR_SET_PDEATHSIG` in crate `libc`
   --> crates/tako/src/launcher.rs:160:41
    |
160 |             let ret = libc::prctl(libc::PR_SET_PDEATHSIG, libc::SIGTERM);
    |                                         ^^^^^^^^^^^^^^^^ not found in `libc`

<img width="583" alt="image" src="https://user-images.githubusercontent.com/44746473/217596221-930a2aaa-ebcf-4a44-b6d4-0971d02a77b3.png">

Is it possible to return to support for also non-linux systems?

**Comment by Kobzol** [comment]
Hi, HQ has been Linux-only from the beginning. It is also one of its design principles, to reduce external dependencies and thus make it easier to install.

Recent versions made it impossible to compile on other OSes, but  there is also runtime behaviour (e.g. autodetection of resources or task pinning) that is Linux specific.

We can resolve the compilation issue relatively easily, but it won't cause HQ to work perfectly on other operating systems.

**Comment by Kobzol** [comment]
Just a note that it should be possible to build HQ on macOS now (we added a check to CI to make sure that it stays that way), however we still do not guarantee any support for its functionality.
