### ISSUE TITLE
resubmitted streaming jobs 

### ISSUE THREAD

**Issue by arashbm** [It4innovations/hyperqueue#584]
let's say I submit a job with multiple tasks, and some of those tasks fail. If I try to resubmit the failed tasks, the resubmitted job instantly fails.

```con
$ hq submit --array=0-4 --log=output.log bash some_script.sh
$ # a while later...
$ hq job resubmit 1 --filter=failed,canceled
```

The server logs:
```
ERROR Stream connection ended with: Job 2 is not registered for streaming
```

Expected behaviour, to me at least, is that the new job just appends to the original log.

**Comment by Kobzol** [comment]
Hi! Thanks for posting this issue. The combination of output streaming and resubmission is not currently implemented at the moment. However, as you can see, the error message is not very good.

As a short term solution, we will improve the error message to let users know that this is not currently supported. In longer term, we plan to implement support for it (we were basically waiting for the first use-case that would need it, seems like you're the first one :) ).

**Comment by Kobzol** [comment]
This is no longer relevant, because we have since removed resubmit completely.

**Comment by spirali** [comment]
Let me note that the mechanism that is recommended now for resubmitting do not suffer with this kind error. However, as appending to log is not implemented, resubmit of the task will overwrite the log file.
