### ISSUE TITLE
ARM build?

### ISSUE THREAD

**Issue by vsoch** [It4innovations/hyperqueue#609]
Heyo! Any chance we could add an ARM build to the set?

![image](https://github.com/It4innovations/hyperqueue/assets/814322/a267e2d3-4c82-43d7-8224-130bc2cc1333)

I'd like to test my operator on ARM graviton instances on AWS, and I think it will error if it's not the right architecture. For the operators I maintain (for ARM images) the build is a little long to test for CI, but I have it build on merge into the main branch. You could do something similar with releases (or maybe you already do!)

**Comment by Kobzol** [comment]
Hi, would this target be OK for you? (taken from https://doc.rust-lang.org/nightly/rustc/platform-support.html)

aarch64-unknown-linux-gnu:ARM64 Linux (kernel 4.1, glibc 2.17+)

**Comment by vsoch** [comment]
yes, that looks like the right one!

**Comment by vsoch** [comment]
Also if you aren't able to provide a release here, if you show me the changes to do I could put them in the production container I'm using instead. I know building ARM on GitHub actions (well, at least with QEMU) is really slow.

**Comment by Kobzol** [comment]
Can you please check if [this](https://github.com/It4innovations/hyperqueue/suites/14511833767/artifacts/820618296) artifact works for you?

**Comment by vsoch** [comment]
Testing now!

**Comment by vsoch** [comment]
okay the initial container built - the executable looks OK to run (and lammps is good too) I need to next put them together in a Kubernetes setup with the hyperqueue-operator then I can give you a final answer if all is working!

**Comment by Kobzol** [comment]
So, did it work? :)

**Comment by vsoch** [comment]
Oh I forgot to post an update! And I'm forgetting now myself :laughing: I do remember that I added arm support https://github.com/converged-computing/hyperqueue-operator/pull/5/files and I vaguely remember testing, but I don't recall the details. I'm pretty booked until I can record two talks, but I (think?) it worked and I would say it's OK to make a proper release. I'll add a note to my TODO for after these talks to give it one more test. And darn I wish I had remembered to update here months ago - I don't remember to give you more detail than that!

**Comment by vsoch** [comment]
oh! I just remembered (right after I posted of course, lol). So we also needed JobSet for arm, but I haven't heard anything on that issue. https://github.com/kubernetes-sigs/jobset/issues/237. I think I was able to bring up the arm images but not actually get everything running. I'll ping them again now.
