### ISSUE TITLE
Typo in srun command, multinode.md

### ISSUE THREAD

**Issue by linusseelinger** [It4innovations/hyperqueue#682]
Currently, the srun command in multinode.md reads

```
#!/bin/sh

srun --nodefile $HQ_NODE_FILE --nodes=$HQ_NUM_NODES mpirun ...
```

Probably should be 

```
#!/bin/sh

srun --nodefile=$HQ_NODE_FILE --nodes=$HQ_NUM_NODES mpirun ...
```

At least according to `man srun` on my cluster:

` -F, --nodefile=<node_file>`

**Comment by Kobzol** [comment]
Umm, I would assume that most production ready software that isn't a toy implementation has a CLI parser that accepts long arguments both in the `--<key>=<val>` and `--<key> <val>` form :) It seems to work fine on our Slurm cluster, let me know if you encounter any problems without the equal sign on your cluster.

**Comment by Kobzol** [comment]
Oh, I didn't notice that. Yeah, good point, in that case we should probably use `=` in both places :)
