### ISSUE TITLE
Error with PythonAPI : stdout/-err = None 

### ISSUE THREAD

**Issue by Pengu1ne** [It4innovations/hyperqueue#691]
Hi!

I just updated my HyperQueue (with Python API) to the newest version (v018). I tried to run it, but I got an error:
```
hyperqueue.validation.ValidationException: Invalid value provided for `stdout`: <class 'NoneType'>. Expected str, Path or `StdioDef`.
```

The specific line looks something like:
```
            arg_params =(parameters,
                         syst_name,
                         input)
            job.function(calc_process,
                         args=arg_params,
                         stdout=None,
                         stderr=None)

```

I tested that HyperQueue + my application runs without a problem with v016. I tracked the changes and noticed that after v016, the stdout and stderr are changed. Because v016 works for me, I can use it, but just that you are aware if this not in purpose.

**Comment by Kobzol** [comment]
This was not intended, thank you for reporting it.
