### ISSUE TITLE
Support for giving slurm jobs of workers different names

### ISSUE THREAD

**Issue by StHagel** [It4innovations/hyperqueue#708]
Currently, all workers are just named `hq-alloc` in slurm, when viewing them in `squeue`.
It would be nice to be able to give the workers custom names. In slurm this can be done via the `--job-name='My job name'` flag.

**Comment by Kobzol** [comment]
If you execute `hq alloc add --name <foo>` and then all allocations from this queue would be named `<foo>`, would that be OK for you? Or should it be e.g. `<foo>-1`, `<foo>-2` etc.?

**Comment by StHagel** [comment]
Would it also be possible to add a flag to `hq submit` instead of `hq alloc`?

**Comment by Kobzol** [comment]
You can already state the name of a job (`hq submit --name <foo>`), but this has nothing to do with allocations. Note that HQ jobs are completely separated from allocations, and therefore any attribute of a job cannot affect attributes of Slurm/PBS allocations.

**Comment by StHagel** [comment]
Right, makes sense.

Then having a `--name` flag available for `hq alloc` seems reasonable. Would the index in the name indicate a worker?

**Comment by Kobzol** [comment]
The index would indicate the order of the allocation created in the given allocation queue. So the first allocation created by HQ would get `<foo>-1`, the second one would get `<foo>-2`, etc. In theory, we could also let the allocator name the workers, currently they get their name from the hostname of the node on which they are spawned.

(The flag is already available btw, it just isn't propagated to the Slurm allocation name, which is what we could change).

**Comment by Kobzol** [comment]
Oops, according to our documentation, the `--name` parameters should already have been used to name the allocations, so this was actually a bug. Fixed by https://github.com/It4innovations/hyperqueue/pull/710.
