### ISSUE TITLE
job info: add worker machine info into JSON output

### ISSUE THREAD

**Issue by svatosFZU** [It4innovations/hyperqueue#735]
Hi,
there is a bit of inconsistency between output of job list in plain and JSON format. In the plain output, there is "Workers" value showing on which machine the worker is running:
```
[svatosm@login1.barbora ~]$ /home/svatosm/hq-v0.16.0-linux-x64/hq job info 5036
+----------------------+-------------------------+
| ID                   | 5036                    |
| Name                 | bash                    |
| State                | RUNNING                 |
| Tasks                | 1; Ids: 0               |
| Workers              | cn65.barbora.it4i.cz    |
| Resources            | cpus: 36 compact        |
| Priority             | 0                       |
| Command              | bash                    |
| Stdout               | <None>                  |
| Stderr               | <None>                  |
| Environment          |                         |
| Working directory    | /home/svatosm           |
| Task time limit      | None                    |
| Crash limit          | 1                       |
| Submission date      | 2024-08-01 06:07:06 UTC |
| Submission directory | /home/svatosm           |
| Makespan             | 2h 8m                   |
+----------------------+-------------------------+
```
In the JSON output mode, this information is missing
```
[svatosm@login1.barbora ~]$ /home/svatosm/hq-v0.16.0-linux-x64/hq job info 5036 --output-mode json
[
  {
    "crash_limit": 1,
    "finished_at": null,
    "info": {
      "id": 5036,
      "name": "bash",
      "task_count": 1,
      "task_stats": {
        "canceled": 0,
        "failed": 0,
        "finished": 0,
        "running": 1,
        "waiting": 0
      }
    },
    "max_fails": null,
    "pin_mode": null,
    "priority": 0,
    "program": {
      "args": [
        "bash"
      ],
      "cwd": "/home/svatosm",
      "env": {},
      "stderr": null,
      "stdout": null
    },
    "resources": [
      {
        "min_time": 39600.0,
        "n_nodes": 0,
        "resources": [
          {
            "request": {
              "Compact": 36
            },
            "resource": "cpus"
          }
        ]
      }
    ],
    "started_at": "2024-08-01T06:07:05.781232209Z",
    "submit_dir": "/home/svatosm",
    "task_dir": false,
    "tasks": [
      {
        "cwd": "/home/svatosm",
        "id": 0,
        "started_at": "2024-08-01T06:50:15.618736312Z",
        "state": "running",
        "stderr": null,
        "stdout": null,
        "worker": 4855
      }
    ],
    "time_limit": null
  }
]
```
As I would find it useful for monitoring to have this information in the JSON, I would like to ask for addition of this.

**Comment by svatosFZU** [comment]
Hi,
yes, thanks, this is sufficient for my use-case. It is just the inclusion would make the job info more consistent and it would save additional HQ call and matching between jobs and workers.

**Comment by Kobzol** [comment]
I understand, but in this case full consistency between the two output modes is actually not desired. The default (CLI) mode displays a subset of information rendered into a human-readable format, which should be hopefully easy to understand for humans. On the other hand, the JSON output mode should output all available information, in a very verbose and machine-readable way, without including redundant information. This can be seen e.g. in the case of CPU resources, where the JSON mode outputs a very complicated internal representation of worker resources, while the CLI mode just prints something like "1x4 cores".

Of course, if some information is actually missing in the JSON output and cannot be found by other means, then that's a bug in HQ, but I don't think that's what happens in this specific case.

**Comment by svatosFZU** [comment]
OK, as there is a workaround for this, I think the ticket can be closed.

**Comment by spirali** [comment]
If I am not wrong, CLI output actually internally does the the extra call to resolve Worker Ids to hostnames and it is called every time "job info" is called as it is stateless. JSON approach allows to cache worker hostnames, as for given WorkerID, hostname will always be the same (WorkerIds are never reused in a single instance of the server), so if you already know all worker Ids, you do not need to get hostname information from the server.
