### ISSUE TITLE
Python API to Launch Workers with Srun

### ISSUE THREAD

**Issue by manuel-g-castro** [It4innovations/hyperqueue#773]
Hello! I am building a script to be executed within a Slurm or PJM (Fujitsu's scheduler) allocation.  I want to start one worker per node in the allocation, so the current working implementation in Slurm uses `srun`:

```bash
srun --overlap -N 1 -n 1 -c 112 $HQ_PATH/hq worker start --cpus=2x56 --manager slurm 
```

I am wondering if I can do the same with the Python API.

**Comment by Kobzol** [comment]
Hi, the easiest way to start workers is through [Automatic allocation](https://it4innovations.github.io/hyperqueue/stable/deployment/allocation/), which does indeed start one worker per node in the allocation by default. However, the Python API is currently only useful for defining jobs. It can also start a simple local cluster for experiments, but we don't currently expose the automatic allocation interface through the Python API. Therefore, automatic allocation either needs to be started from the CLI, or you can just run the CLI commands from Python.

We plan to add this in the future, but it's not currently a high priority item.

**Comment by manuel-g-castro** [comment]
Okayy! Thanks, @Kobzol !
