### ISSUE TITLE
error: unexpected argument '--log' found 

### ISSUE THREAD

**Issue by Younthing** [It4innovations/hyperqueue#789]
![image](https://github.com/user-attachments/assets/4de1d7d6-1be2-40aa-9a04-656effe196ab)

"While using hq version 0.20 with Nextflow pipeline, I encountered an error: 'unexpected argument --log found'. Although removing the --log argument resolves the error, I need this parameter as it's automatically generated by Nextflow. I believe this might be a compatibility issue between hq 0.20 and Nextflow's default logging functionality. Could you please advise on how to properly handle the --log parameter in this version?"

**Comment by Younthing** [comment]
nextflow 24.10.2  should  use hq 0.17.0

**Comment by bguo068** [comment]
> nextflow 24.10.2 should use hq 0.17.0

This combination of versions is a nice workaround.
